[package]
name = "camonano"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
client = { path = "client", version = "0.1.0" }
thiserror = "1.0.49"
zeroize = { version = "1.6.0", features = ["zeroize_derive"] }
rand = "0.8.5"
hex = "0.4.3"
log = { version = "0.4.21", features = ["std"] }
serde = { version = "1.0.196", features = ["derive"] }
bincode = "1.3.3"
argon2 = "0.5.3"
tokio = { version = "1.33.0", features = ["full"] }
clap = { version = "4.4.10", features = ["derive"] }
confy = { version = "0.6.0", default-features = false, features = ["yaml_conf"] }
rpassword = "7.3.1"
aes-gcm = "0.10.3"