name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build-macos:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build (CLI)
      run: cargo build --verbose
      working-directory: ./cliwallet

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build (CLI)
      run: cargo build --verbose
      working-directory: ./cliwallet

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build (CLI)
      run: cargo build --verbose
      working-directory: ./cliwallet

  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run Tests
      run: cargo test --verbose --all-targets --all-features --workspace
    - name: Run Clippy
      run: cargo clippy --verbose --all-targets --all-features --workspace
