name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build-macos:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build (CLI)
      run: cargo build --verbose

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build (CLI)
      run: cargo build --verbose

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build (CLI)
      run: cargo build --verbose

  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build (client)
      run: cargo build --verbose
      working-directory: ./client
    - name: Run Tests (client)
      run: cargo test --verbose --all-features
      working-directory: ./client

    - name: Build (core_client)
      run: cargo build --verbose
      working-directory: ./core_client
    - name: Run Tests (core_client)
      run: cargo test --verbose --all-features
      working-directory: ./core_client

    - name: Run Tests (CLI)
      run: cargo test --verbose --all-features
    - name: Run Clippy (CLI)
      run: cargo clippy --all-targets --all-features